/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FavoriteArtists;

import IdConnection.Requetes;
import IdConnection.Parametres;

public class App {
   
    public static void main(String[] args) {

    	
    	
    }
}
