///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package deezer;
//
//import java.sql.SQLException;
//import java.util.List;
//
//import deezer.IdConnection.Requetes;
//import deezer.IdConnection.Session;
//import deezer.model.Artist;
//import deezer.model.Track;
//
///**
// * Point d'entrée de l'application. Les tests sont lancés ici.
// * 
// * @author Tony/Olivier/Nicolas
// *
// */
//public class App 
//{
//    
//
//    public static void main(String[] args) throws SQLException 
//    {
//		Session sqlSession = new Session();
//
//		// TESTS
//		System.out.println("\n>>> afficheTable");
//		Requetes.afficheTable(sqlSession.getConnection(), Requetes.ARTISTS);
//		
//		System.out.println("\n>>> getArtistsByName");
//		Artist u = Requetes.getArtistsByName(sqlSession.getConnection(), "Eminem");
//		System.out.println(u);
//
//		System.out.println("\n>>> getAllArtists");
//		List<Artist> artListe = Requetes.getAllArtists(sqlSession.getConnection());
//		for (Artist artiste : artListe) 
//		{
//			System.out.println(artiste);
//		}
//		
//		
//		System.out.println("\n>>> UPDATE");
//		Artist delegue = new Artist(1, "Eminem", 50000);
//		Requetes.updateArtists(sqlSession.getConnection(), delegue);
//		Requetes.afficheTable(sqlSession.getConnection(), Requetes.ARTISTS);
//		
//		System.out.println("\n>>> CREATE");
//		Artist delegue2 = new Artist(6, "Yelawolf", 20000);
//		Requetes.createArtists(sqlSession.getConnection(), delegue2);
//		Requetes.afficheTable(sqlSession.getConnection(), Requetes.ARTISTS);
//		
//		System.out.println("\n>>> DELETE");
//		Requetes.deleteArtists(sqlSession.getConnection(), delegue2);
//		Requetes.afficheTable(sqlSession.getConnection(), Requetes.ARTISTS);
//
//    }
//}
//
