/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package FavoriteArtists;
package deezer;

import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.util.Scanner;

import deezer.IdConnection.Session;
import deezer.jdbc.RequetesJDBC;import deezer.model.Artist;


public class App  {
 		
    public static void main(String[] args) throws MalformedURLException, IOException, SQLException 
    { 
        while (true) {
        	menu.CRUD();	
		}   	
    }    	
}