/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package FavoriteArtists;
package deezer;

import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;

//import deezer.IdConnection.Requetes;
import deezer.IdConnection.Session;
import deezer.api.RequetesAPI;
import deezer.model.Album;
import deezer.model.Artist;
import deezer.model.Track;


public class App2  {
   
	private static final String jsonFileName = "sample.json";
	
	public static final String DEEZER_KEY = "6f248857d4mshe4bac8f2b40d35fp14b7abjsn29fb62695aae";
	
	
	/*
	public static void titreDeezer (String artiste) throws MalformedURLException, IOException
	{
		String url = "https://api.deezer.com/search/track/?q="+artiste+"&index=0&output=java";
		
		String jsonText = IOUtils.toString(new URL(url), Charset.forName("UTF-8"));
		writeJson(jsonText);
		JSONObject jsonComplet = new JSONObject(jsonText);
		
		int totalCount = jsonComplet.getInt("total");
		System.out.println("total count : " + totalCount);
		
		JSONArray titreListe = jsonComplet.getJSONArray("data");
		for (int i = 0; i < Math.min(10, titreListe.length()); i++)
		{
			JSONObject current = titreListe.getJSONObject(i);
			System.out.println("titre : "+current.getString("title"));
			System.out.println("durée du morceau (en secondes): "+current.getInt("duration")); 
			System.out.println("rang : "+current.getInt("rank")); 

		}
	}
	*/	
	
		
    public static void main(String[] args) throws MalformedURLException, IOException, SQLException 
    { 
    	Session session = new Session();
       	//Artist art = RequetesAPI.artisteDeezer(session.getConnection(), "supertramp");
       	//Artist art2  = RequetesAPI.artisteDeezer(session.getConnection(), "people");
       	Album alb = RequetesAPI.albumDeezer(session.getConnection(), "the eminem show");
       	Track ttr = RequetesAPI.titreDeezer(session.getConnection(), "pookie");
    }
}